### ISSUE TITLE
v1.0.3 tagged incorrectly for go install

### ISSUE THREAD

**Issue by sarahhodne** [nzlosh/spf_packer#6]
I've noticed that running `go install github.com/nzlosh/spf_packer@latest` installs 1.0.0 instead of 1.0.3. I think this is because the tag name for 1.0.3 is `1.0.3` instead of `v1.0.3`.

Would it be possible to get a tag named `v1.0.3` for the same commit as well, so Go installs the actual latest version?

**Comment by nzlosh** [comment]
Thanks for pointing this out.  A new release has been made available with the expected tag format.

**Comment by sarahhodne** [comment]
Can confirm that `go install github.com/nzlosh/spf_packer@latest` now installs 1.1.0, thanks!

```
❯ go install github.com/nzlosh/spf_packer@latest
go: downloading github.com/nzlosh/spf_packer v1.1.0
```
